ipod_log_pattern = r'^(\d+):(\d+):(\d+):(.+)$'

lastfm_root = 'http://ws.audioscrobbler.com'
user_auth_root = 'http://www.last.fm/api/auth'
song_extensions = ['.mp3', '.flac']

# http://ocelma.net/last.fm-genre-tagcloud/index.html
all_genres = set(
    "3rd wave ska",
    "60s pop",
    "77 style punk",
    "80s",
    "80s hair metal",
    "80s hardcore",
    "80s metal",
    "80s pop",
    "80s rock",
    "8bit",
    "90s pop",
    "90s rock",
    "abstract hip-hop",
    "acid",
    "acid house",
    "acid jazz",
    "acoustic",
    "adult alternative",
    "adult contemporary",
    "afrobeat",
    "aggrotech",
    "album rock",
    "alt country",
    "alt rock",
    "alt-country",
    "alt-rock",
    "alternative",
    "alternative and punk",
    "alternative country",
    "alternative dance",
    "alternative metal",
    "alternative pop",
    "alternative pop-rock",
    "alternative rap",
    "alternative rock",
    "ambient",
    "ambient black metal",
    "ambient pop",
    "ambient techno",
    "american punk",
    "anarcho punk",
    "anarcho-punk",
    "angura kei",
    "anti-folk",
    "antifolk",
    "apocalyptic folk",
    "arena rock",
    "art punk",
    "art rock",
    "art-rock",
    "artcore",
    "atmospheric ambient",
    "atmospheric black metal",
    "atmospheric metal",
    "avant-garde",
    "avant-garde jazz",
    "avant-garde metal",
    "avant-prog",
    "avantgarde metal",
    "baroque",
    "baroque pop",
    "bass",
    "batcave",
    "battle metal",
    "beatdown",
    "beats",
    "bebop",
    "belgian music",
    "big band",
    "big beat",
    "bitpop",
    "black death metal",
    "black metal",
    "black music",
    "black y pagan metal",
    "blackened death metal",
    "bluegrass",
    "blues",
    "blues rock",
    "blues-rock",
    "bop",
    "bossa nova",
    "brazilian rock",
    "breakbeat",
    "breakcore",
    "brit pop",
    "brit rock",
    "brit-pop",
    "british",
    "british folk",
    "british invasion",
    "british metal",
    "british punk",
    "british rock",
    "britpop",
    "britrock",
    "broken beat",
    "brutal",
    "brutal death",
    "brutal death metal",
    "c-pop",
    "cabaret",
    "cello rock",
    "celtic",
    "celtic metal",
    "celtic punk",
    "celtic rock",
    "chamber pop",
    "chanson",
    "chicago blues",
    "chick rock",
    "chillout",
    "chiptune",
    "christian hardcore",
    "christian metal",
    "christian metalcore",
    "christian rock",
    "classic",
    "classic blues",
    "classic country",
    "classic jazz",
    "classic metal",
    "classic punk",
    "classic rock",
    "classical",
    "classique",
    "club",
    "club-dance",
    "college rock",
    "comedy rock",
    "contemporary",
    "contemporary christian",
    "contemporary classical",
    "contemporary jazz",
    "contemporary rnb",
    "cool jazz",
    "country",
    "country rock",
    "country-rock",
    "cpop",
    "crack rock steady",
    "crazy",
    "crunk",
    "crust",
    "crust punk",
    "cyber metal",
    "cybergrind",
    "cyberpunk",
    "d-beat",
    "dance",
    "dance punk",
    "dance rock",
    "dance-pop",
    "dance-punk",
    "dark",
    "dark ambient",
    "dark cabaret",
    "dark electro",
    "dark folk",
    "dark metal",
    "dark wave",
    "darkwave",
    "death",
    "death doom",
    "death doom metal",
    "death metal",
    "death punk",
    "death rock",
    "death-doom metal",
    "death-grind",
    "death-thrash metal",
    "deathcore",
    "deathgrind",
    "deathrock",
    "deep ambient",
    "deep house",
    "delta blues",
    "depressive black metal",
    "depressive rock",
    "desert rock",
    "detroit techno",
    "deutschpunk",
    "deutschrap",
    "deutschrock",
    "digital hardcore",
    "dirty south",
    "disco",
    "dnb",
    "doom",
    "doom metal",
    "downbeat",
    "downtempo",
    "dream pop",
    "dreampop",
    "drill n bass",
    "drone",
    "drone doom",
    "drone metal",
    "drum and bass",
    "drum n bass",
    "dub",
    "dubstep",
    "east coast rap",
    "eastern europe rock",
    "ebm",
    "electro",
    "electro pop",
    "electro-industrial",
    "electro-pop",
    "electro-rock",
    "electroclash",
    "electrojazz",
    "electronic",
    "electronic dub",
    "electronic pop",
    "electronic rock",
    "electronica",
    "electropop",
    "electropunk",
    "elektro",
    "emo",
    "emo rock",
    "emo violence",
    "emocore",
    "epic black metal",
    "epic metal",
    "euro trance",
    "eurobeat",
    "eurodance",
    "europop",
    "experimental",
    "experimental metal",
    "experimental rock",
    "experimental techno",
    "extreme metal",
    "extreme power metal",
    "fado",
    "fantasy",
    "fantasy metal",
    "female fronted metal",
    "female vocalists",
    "finnish metal",
    "finnish rock",
    "flamenco",
    "folk",
    "folk and viking metal",
    "folk black metal",
    "folk metal",
    "folk noir",
    "folk punk",
    "folk rock",
    "folk-punk",
    "folk-rock",
    "folktronica",
    "freak folk",
    "free jazz",
    "french house",
    "french pop",
    "french rock",
    "frenchcore",
    "funeral doom",
    "funeral doom metal",
    "funk",
    "funk metal",
    "funk rock",
    "fusion",
    "future pop",
    "futurepop",
    "g-funk",
    "gangsta",
    "gangsta rap",
    "garage punk",
    "garage rock",
    "geek rock",
    "german",
    "german hip hop",
    "german hip-hop",
    "german hiphop",
    "german metal",
    "german metalcore",
    "german rock",
    "girl rock",
    "glam",
    "glam metal",
    "glam rock",
    "glitch",
    "goa",
    "goa trance",
    "goregrind",
    "gospel",
    "goth",
    "goth metal",
    "goth rock",
    "gothenburg metal",
    "gothic",
    "gothic doom metal",
    "gothic metal",
    "gothic rock",
    "grime",
    "grind",
    "grindcore",
    "groove",
    "groove metal",
    "grunge",
    "guitar rock",
    "gypsy punk",
    "hair metal",
    "happy hardcore",
    "hard bop",
    "hard rock",
    "hard trance",
    "hardcore",
    "hardcore and metalcore",
    "hardcore punk",
    "hardcore rap",
    "hardrock",
    "hardstyle",
    "harsh ebm",
    "heavy metal",
    "heavy rock",
    "hip hop",
    "hip-hop",
    "hip-hop and rap",
    "hiphop",
    "horror punk",
    "horrorcore",
    "house",
    "idm",
    "indie",
    "indie electronic",
    "indie folk",
    "indie hip hop",
    "indie pop",
    "indie rap",
    "indie rock",
    "indie-pop",
    "indie-rock",
    "indiepop",
    "indietronic",
    "indietronica",
    "industrial",
    "industrial black metal",
    "industrial death metal",
    "industrial jungle pussy punk",
    "industrial metal",
    "industrial rock",
    "instrumental",
    "instrumental hip-hop",
    "instrumental metal",
    "instrumental rock",
    "irish folk",
    "irish punk",
    "italian pop",
    "j-indie",
    "j-music",
    "j-pop",
    "j-rock",
    "j-urban",
    "jam band",
    "jangle pop",
    "japanese",
    "japanese indie",
    "japanese pop",
    "japanese rock",
    "jazz",
    "jazz funk",
    "jazz fusion",
    "jazz hop",
    "jazz metal",
    "jazz piano",
    "jazz rock",
    "jazz vocal",
    "jazz-rock",
    "jazzy",
    "jpop",
    "jrock",
    "jungle",
    "k-pop",
    "kills nu-metal ten times over",
    "klassik",
    "klezmer",
    "kpop",
    "krautrock",
    "latin",
    "latin jazz",
    "latin rock",
    "liquid funk",
    "lo-fi",
    "lounge",
    "love metal",
    "mallcore",
    "martial industrial",
    "math",
    "math metal",
    "math rock",
    "mathcore",
    "mathmetal",
    "melodeath",
    "melodic black metal",
    "melodic death",
    "melodic death metal",
    "melodic hardcore",
    "melodic metal",
    "melodic metalcore",
    "melodic power metal",
    "melodic punk",
    "melodic rock",
    "mendigao thrash",
    "metal",
    "metalcore",
    "microhouse",
    "minimal",
    "minimal techno",
    "minimalism",
    "minimalist",
    "mittelalter",
    "modern country",
    "modern jazz",
    "modern metal",
    "modern rock",
    "motown",
    "mpb",
    "nederhop",
    "neo classical",
    "neo soul",
    "neo-classical",
    "neo-classical metal",
    "neo-folk",
    "neo-prog",
    "neo-psychedelia",
    "neo-soul",
    "neoclassic",
    "neoclassical",
    "neofolk",
    "nerdcore",
    "neurofunk",
    "new age",
    "new metal",
    "new rave",
    "new wave",
    "new wave of british heavy metal",
    "new weird america",
    "new york punk",
    "new-age",
    "ninja tune",
    "nintendocore",
    "no wave",
    "noise",
    "noise pop",
    "noise rock",
    "noise-rock",
    "noisecore",
    "nordic metal",
    "northern soul",
    "norwegian",
    "norwegian black metal",
    "norwegian metal",
    "not emo",
    "not metal",
    "not rock",
    "nouvelle scene francaise",
    "nsbm",
    "nu jazz",
    "nu metal",
    "nu soul",
    "nu-jazz",
    "nu-metal",
    "nujazz",
    "numetal",
    "nwobhm",
    "oi",
    "old school",
    "old school death metal",
    "old school hardcore",
    "old school industrial",
    "old school punk",
    "old school rap",
    "oldschool hardcore",
    "opera",
    "opera metal",
    "organic ambient",
    "oshare kei",
    "outlaw country",
    "p-funk",
    "pagan black metal",
    "pagan metal",
    "peace punk",
    "piano",
    "polish hip-hop",
    "polish punk",
    "polish rock",
    "political punk",
    "political rap",
    "polski hip hop",
    "pop",
    "pop metal",
    "pop punk",
    "pop rock",
    "pop-punk",
    "pop-rock",
    "poprock",
    "porngrind",
    "post grunge",
    "post hardcore",
    "post punk",
    "post rock",
    "post-black metal",
    "post-bop",
    "post-emo",
    "post-grunge",
    "post-hardcore",
    "post-metal",
    "post-punk",
    "post-rock",
    "postpunk",
    "postrock",
    "power metal",
    "power pop",
    "power violence",
    "powernoise",
    "powerpop",
    "powerviolence",
    "prog metal",
    "prog rock",
    "prog-rock",
    "progressive",
    "progressive black metal",
    "progressive death metal",
    "progressive house",
    "progressive metal",
    "progressive power metal",
    "progressive rock",
    "progressive trance",
    "proto punk",
    "proto-punk",
    "psy",
    "psychedelia",
    "psychedelic",
    "psychedelic folk",
    "psychedelic rock",
    "psychedelic trance",
    "psychill",
    "psychobilly",
    "psytrance",
    "pub rock",
    "punk",
    "punk cabaret",
    "punk pop",
    "punk revival",
    "punk rock",
    "punk-pop",
    "punk-rock",
    "punkrock",
    "r and b",
    "r&b",
    "ragga",
    "raggacore",
    "rap",
    "rap and hip hop",
    "rap and hip-hop",
    "rap metal",
    "rap-metal",
    "rap-rock",
    "rapcore",
    "rave",
    "raw black metal",
    "real hip hop",
    "real hip-hop",
    "real metal",
    "real screamo",
    "reggae",
    "reggae-dub-ska",
    "retro",
    "rhythm and blues",
    "riot grrl",
    "riot grrrl",
    "ritual ambient",
    "rnb",
    "rock",
    "rock and roll",
    "rock argentino",
    "rock argento",
    "rock francais",
    "rock n roll",
    "rock opera",
    "rockabilly",
    "rocksteady",
    "roots reggae",
    "russian alternative",
    "russian rock",
    "sadcore",
    "salsa",
    "samba",
    "scandinavian metal",
    "screamo",
    "seen live",
    "semi-ambient",
    "shibuya-kei",
    "shock rock",
    "shoegaze",
    "shoegazer",
    "sid metal",
    "singer-songwriter",
    "ska",
    "ska punk",
    "ska-punk",
    "skacore",
    "skapunk",
    "skate punk",
    "skatepunk",
    "slowcore",
    "sludge",
    "sludge metal",
    "smooth jazz",
    "soft rock",
    "soul",
    "soundtrack",
    "southern rap",
    "southern rock",
    "space age pop",
    "space ambient",
    "space music",
    "space rock",
    "spanish metal",
    "spanish pop",
    "spanish rock",
    "speed metal",
    "stoner doom",
    "stoner metal",
    "stoner rock",
    "straight edge",
    "straight edge hardcore",
    "street punk",
    "streetpunk",
    "sub pop",
    "suicidal black metal",
    "suomirock",
    "surf",
    "surf rock",
    "swedish death metal",
    "swedish metal",
    "swedish pop",
    "swedish punk",
    "swing",
    "symphonic",
    "symphonic black metal",
    "symphonic metal",
    "symphonic power metal",
    "symphonic prog",
    "symphonic rock",
    "synth pop",
    "synth rock",
    "synth-pop",
    "synth-rock",
    "synthpop",
    "tango",
    "tech metal",
    "technical death",
    "technical death metal",
    "technical metal",
    "technical thrash metal",
    "techno",
    "teen pop",
    "terror ebm",
    "thrash",
    "thrash metal",
    "thrashcore",
    "traditional doom metal",
    "trance",
    "trash metal",
    "tribal ambient",
    "trip hop",
    "trip-hop",
    "triphop",
    "troll metal",
    "tropicalia",
    "true black metal",
    "true metal",
    "true norwegian black metal",
    "true punk",
    "turkish rock",
    "turntablism",
    "twee pop",
    "uk hip hop",
    "underground",
    "underground hip hop",
    "underground hip-hop",
    "underground rap",
    "uplifting trance",
    "urban",
    "video game",
    "video game music",
    "viking metal",
    "visual kei",
    "vocal house",
    "vocal jazz",
    "vocal trance",
    "west coast rap",
    "wizard rock",
    "world",
    "world fusion",
    "world music",
    "wristslitters"
)