name: Bug Report
description: Report a bug or issue with iPod Wrapped
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the info below so I can help you out.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is
      placeholder: Tell me what went wrong!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g., Arch Linux 6.17.6, macOS 14.2, Windows 11
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., Python 3.13.0
    validations:
      required: true

  - type: input
    id: ipod-model
    attributes:
      label: iPod Model & Rockbox Version
      description: What iPod model and Rockbox version are you using?
      placeholder: e.g., iPod Classic 6th Gen, Rockbox 3.15

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, error messages, or logs here
      placeholder: |
        Error messages, stack traces, or any other helpful info...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting, please confirm
      options:
        - label: I have checked existing issues to make sure this isn't a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
