name: Feature Request
description: Suggest a new feature or enhancement for iPod Wrapped
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Hi!! Thanks for suggesting a new feature. Enhancement suggestions are SO incredibly welcome! Let me know what you're thinking.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear description of what you'd like to see
      placeholder: I would love if the app could...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain why this would be useful and who would benefit from it
      placeholder: This would be helpful because...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
      placeholder: |
        It could work by...
        Maybe add a button that...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples here
      placeholder: |
        Here's an example from another app...
        I made a quick mockup...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please confirm
      options:
        - label: I have checked the TODO list in the README to make sure this isn't already planned
          required: true
        - label: I have checked existing issues/PRs to avoid duplicates
          required: true
